#! /usr/bin/env ruby

require 'rubygems'
require 'algoliasearch'
require 'open-uri'
require 'tempfile'

# download list of plugins
urls = Tempfile.new('urls')
File.open(urls.path, 'w') do |f|
  content = open('http://plugins.svn.wordpress.org/').read
  f << content.scan(/<li><a href="([^"]+)\/">/).map { |name| "https://api.wordpress.org/plugins/info/1.0/#{name[0]}.json" }.join("\n")
end

# download all plugins using an advanced ruby threading mechanism :)
infos = []
Dir.mktmpdir('jsons') do |temp_dir|
  `cd #{temp_dir} && (cat #{urls.path} | xargs -P 16 wget --quiet)`

  infos << Dir["#{temp_dir}/*.json"].map { |f| JSON.parse(File.read(f)) rescue nil }.compact
end

# cleanup
objects = infos.map do |info|
  begin
    info['author'] = info['author'].gsub(/<[^>]+>/, '') rescue nil
    info['tags'] = info['tags'].values rescue []
    info.delete('compatibility')
    info
  rescue
    nil
  end
end.compact

# push
Algolia.init application_id: ENV['APPLICATION_ID'], api_key: ENV['API_KEY']
index = Algolia::Index.new("#{ENV['INDEX_PREFIX']}_plugins")
index.clear
index.set_setting({
  attributesToIndex: ['unordered(tags)', 'unordered(name)', 'author', 'unordered(short_description)', 'unordered(sections.description)'],
  customRanking: ['desc(downloaded)'],
  attributesForFaceting: ['author', 'tags']
})
index.add_objects(objects)
