#! /usr/bin/env ruby

require 'rubygems'
require 'algoliasearch'
require 'open-uri'
require 'tempfile'

puts "Initializing..."

Algolia.init application_id: ENV['APPLICATION_ID'], api_key: ENV['API_KEY']
index = Algolia::Index.new("#{ENV['INDEX_PREFIX']}_plugins_tmp")
index.set_settings({
  attributesToIndex: ['unordered(tags)', 'unordered(name)', 'author', 'unordered(short_description)', 'unordered(sections.description)'],
  customRanking: ['desc(downloaded)'],
  attributesForFaceting: ['author', 'tags']
})

puts "Listing..."

# download list of plugins
urls = Tempfile.new('urls')
File.open(urls.path, 'w') do |f|
  content = open('http://plugins.svn.wordpress.org/').read
  f << content.scan(/<li><a href="([^"]+)\/">/).map { |name| "https://api.wordpress.org/plugins/info/1.0/#{name[0]}.json" }.join("\n")
end

Dir.mktmpdir('jsons') do |temp_dir|
  puts "Crawling..."

  # download all plugins using an advanced ruby threading mechanism :)
  `cd #{temp_dir} && (cat #{urls.path} | xargs -P 16 wget --quiet)`

  puts "Pushing..."

  # collect infos + push by slice of 1000
  Dir["#{temp_dir}/*.json"].each_slice(1000) do |paths|
    # parse JSON
    infos = paths.map { |f| JSON.parse(File.read(f)) rescue nil }.compact

    # cleanup
    objects = infos.map do |info|
      begin
        info['author'] = info['author'].gsub(/<[^>]+>/, '') rescue nil
        info['tags'] = info['tags'].values rescue []
        info.delete('compatibility')
        info
      rescue
        nil
      end
    end.compact

    # push
    index.add_objects(objects)
  end

  Algolia.move_index index.name, "#{ENV['INDEX_PREFIX']}_plugins"
end

puts "Done"
